.TH wildmidi.cfg 3 "January 2009" WildMIDI "Programming Manual"
.SH NAME
wildmidi.cfg -\ cofigration file for libWildMIDI
.SH DESCRIPTION
.SH SYNTAX
.TP
.BI "dir " "directory"

.TP
.BI "source  " "file"

.TP
.BI "bank " "number"

.TP
.BI "drumset " "number"

.TP
.BI "number " "filename [options]"

.RS
.B OPTIONS
.TP
.B amp=number

.TP
.B note=number

.TP
.B keep=loop|env

.TP
.B remove=sustain

.TP
.B env_time#=number

.TP
.B env_level#=number

.RE

.SH AUTHOR
Chris Ison <wildcode at users.sourceforge.net>
.SH SEE ALSO
.BR wildmidi.cfg (5),
.BR WildMIDI_Init (3),
.BR WildMIDI_GetString (3),
.BR WildMIDI_MasterVolume (3),
.BR WildMIDI_Open (3),
.BR WildMIDI_OpenBuffer (3),
.BR WildMIDI_LoadSamples (3),
.BR WildMIDI_GetOutput (3),
.BR WildMIDI_SetOption (3),
.BR WildMIDI_GetInfo (3),
.BR WildMIDI_FastSeek (3),
.BR WildMIDI_SampledSeek (3),
.BR WildMIDI_Close (3),
.BR WildMIDI_Shutdown (3)


