.TH WildMIDI_LoadSamples 3 "January 2009" WildMIDI "Programming Manual"
.SH NAME
WildMIDI_LoadSamples -\ Depreciated
.SH SYNOPSIS
.B #include <wildmidi_lib.h>
.
.B int WildMidi_LoadSamples ( midi * 
.I handle);
.SH DESCRIPTION
Depreciated from previous version due to libWildMidi not requiring to pre-load samples at this time.
.SH AUTHOR
Chris Ison <wildcode at users.sourceforge.net>
.SH SEE ALSO
.BR wildmidi.cfg (5),
.BR WildMidi_Init (3),
.BR WildMidi_GetString (3),
.BR WildMidi_MasterVolume (3),
.BR WildMidi_Open (3),
.BR WildMidi_OpenBuffer (3),
.BR WildMidi_LoadSamples (3),
.BR WildMidi_GetOutput (3),
.BR WildMidi_SetOption (3),
.BR WildMidi_GetInfo (3),
.BR WildMidi_FastSeek (3),
.BR WildMidi_SampledSeek (3),
.BR WildMidi_Close (3),
.BR WildMidi_Shutdown (3)


