.\" WildMidi_SetOption.3
.\" 
.\" Midi Wavetable Processing library
.\"
.\" Copyright (C)2001-2008 Chris Ison
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\" 
.\" Email: cisos@bigpond.net.au
.\" 	wildcode@users.sourceforge.net
.\" 
.\"	$Id: WildMidi_SetOption.3,v 1.2 2008/05/19 03:47:29 wildcode Exp $
.\"
.TH WildMidi_SetOption 3 2008-05-19 "" "WildMidi Programmer's Manual"
.SH NAME
WildMidi_SetOption \- Set a library option for a specific midi
.SH LIBRARY
.B libWildMidi
.SH SYNOPSIS
.nf
.B #include <wildmidi_lib.h>
.sp
.BI "int WildMidi_SetOption (midi * " handle, " unsigned short int " options, " unsigned short int " setting);
.fi
.SH DESCRIPTION
Set a library option for a specific midi.
.sp
.TP
.B handle
The identifier for the midi this option is to effect that was previously returned by
.BR WildMidi_Open (3)
.sp
.TP
.B options
The option or options you wish to change.
.sp
.IP
.B WM_MO_LOG_VOLUME
The library uses volume levels typically found in computer hardware. These can differ somewhat to volume levels used by midi hardware such as keyboards. This option sets the volume levels to what you'd expect on good quality midi hardware.
Use this option if you intend playing midi files created on midi hardware.
.sp
.IP
.B WM_MO_ENHANCED_RESAMPLING
By default, this library uses triangle interpolation for the resampling of the sound samples. Setting this option enables the library to use a cobination of newton and 34 point guass based interpolation. There is a short delay when initializing the library with this option.
.sp
Note:
.BR WildMidi_GetOutput (3)
will be slower during use due to the work involved in doing the interpolation.
.sp
.IP
.B WM_MO_REVERB
libWildMidi 0.2.3 has an 8 reflection modeled reverb engine, tuned to give more depth to the output without noticable echo. Use this option to give more depth to the output.
.sp
Note:
.BR WildMidi_GetOutput (3)
will be slower during use due to the work involved in doing the reverb.
.sp
.TP
.B setting
To turn on an option, repeat that option here.
To turn off an option, do not put the option here.
.sp
.IP
Example: To turn on Reverb, WildMidi_SetOption(handle, WM_MO_REVERB, WM_REVERB);
.IP
Example: To turn off Reverb, WildMidi_SetOption(handle, WM_MO_REVERB, NULL);

.SH "RETURN VALUE"
returns -1 on error, otherwise returns 0
.SH SEE ALSO
.Xr WildMidi_GetString 3 ,
.Xr WildMidi_Init 3 ,
.Xr WildMidi_MasterVolume 3 ,
.Xr WildMidi_Open 3 ,
.Xr WildMidi_OpenBuffer 3 ,
.Xr WildMidi_GetOutput 3 ,
.Xr WildMidi_GetInfo 3 ,
.Xr WildMidi_FastSeek 3 ,
.Xr WildMidi_Close 3 ,
.Xr WildMidi_Shutdown 3

