.TH WildMidi_GetOutput 3 "January 2009" WildMIDI "Programming Manual"
.SH NAME
WildMidi_GetOutput -\ Retrieve Sample Date.
.SH SYNOPSIS
.B #include <wildmidi_lib.h>
.
.B int WildMidi_GetOutput (midi * 
.I handle,
.B char * 
.I buffer,
.B unsigned long int
.I size);
.SH DESCRIPTION
.B WildMidi_GetOutput()
stores
.I size
bytes of 16bit stereo audio data into
.I buffer
.SH OPTIONS
.TP
.B buffer
.TP
.B size
.SH RETURN VALUE
.TP
.B ammount of buffer used
if the buffer ammount used is less than the size you allocated then libWildMIDI has finished processing the MIDI.
.BR WildMidi_Close (3)
will need to be called if you don't want to do anything more with the midi.
.TP
.B -1
What did I screw up now?
.SH DIAGNOSTICS
.TP
.B size not a multiple of 4
remember, the buffer stores 16bit stereo data, which means is needs 4 bytes just to store 1 sample. Keep
.I size
a multiple of 4 to avoid this error.
.SH BUGS
Return value a signed int and size is an unsigned int. Please limit 
.I size
to no more than 32768 bites.
.SH AUTHOR
Chris Ison <wildcode at users.sourceforge.net>
.SH SEE ALSO
.BR wildmidi.cfg (5),
.BR WildMidi_Init (3),
.BR WildMidi_GetString (3),
.BR WildMidi_MasterVolume (3),
.BR WildMidi_Open (3),
.BR WildMidi_OpenBuffer (3),
.BR WildMidi_LoadSamples (3),
.BR WildMidi_GetOutput (3),
.BR WildMidi_SetOption (3),
.BR WildMidi_GetInfo (3),
.BR WildMidi_FastSeek (3),
.BR WildMidi_SampledSeek (3),
.BR WildMidi_Close (3),
.BR WildMidi_Shutdown (3)


