.TH WildMidi_GetInfo 3 2010-06-03 "" "WildMidi Programmer's Manual"
.SH NAME
WildMidi_GetInfo \- get information on a midi
.SH LIBRARY
.B libWildMidi
.SH SYNOPSIS
.nf
.B #include <wildmidi_lib.h>
.sp
.BI "struct _WM_Info * WildMidi_GetInfo (midi * " handle);
.fi
.SH DESCRIPTION
.B struct _WM_Info {
.br
.BI "   unsigned char * " copyright;
.br
.BI "   unsigned long int " current_sample;
.br
.BI "   unsigned long int " approx_total_samples;
.br
.BI "   unsigned short int " mixer_options;
.br
.B };
.br
.SH SEE ALSO
.BR WildMidi_GetString (3) ,
.BR WildMidi_Init (3) ,
.BR WildMidi_MasterVolume (3) ,
.BR WildMidi_Open (3) ,
.BR WildMidi_OpenBuffer (3) ,
.BR WildMidi_SetOption (3) ,
.BR WildMidi_GetOutput (3) ,
.BR WildMidi_GetInfo (3) ,
.BR WildMidi_FastSeek (3) ,
.BR WildMidi_SampledSeek (3),
.BR WildMidi_Close (3) ,
.BR WildMidi_Shutdown (3),
.BR wildmidi (1),
.BR wildmidi.cfg (5)
.SH BUGS
.SH AUTHOR
Chris Ison <wildcode@users.sourceforge.net>
.SH COPYRIGHT
Copyright (C) 2001-2010 Chris Ison
.sp
This file is part of WildMIDI.
.sp
WildMIDI is free software: you can redistribute and/or modify the player under the terms of the GNU General Public License and you can redistribute and/or modify the library under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the licenses, or(at your option) any later version.
.sp
WildMIDI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License and the GNU Lesser General Public License for more details.
.sp
You should have received a copy of the GNU General Public License and the GNU Lesser General Public License along with WildMIDI. If not, see <http://www.gnu.org/licenses/>.
.sp
